# Generated by Django 3.0.3 on 2020-02-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='adventure_image'),
        ),
    ]
